### PR TITLE
Ignore null value and empty collection

### PR DESCRIPTION
**Pull request by pvgnd**
This PR adds two configuration variables to the ItemNormalizer to ignore null value and empty collection.
The default behavior is unchanged as these configurations are set to false by default.

### CODE REVIEW

**Comment by dunglas** [comment]
Wouldn't be more flexible to pass such parameters in the `$context` parameter? As a side bonus, the behavior become configurable on a per-resource basis.

**Comment by dunglas** [comment]
Btw, what's the use case of doing so?

**Comment by theofidry** [comment]
What do you mean by ignoring? Completely exclude the property from the JSON? If so maybe it's a little bit too specific, having an API for which the properties of a resource differs from one to another seems very... unsettling. It's definitely more troublesome to handle on the client side and the only advantage I see would be to have less properties in the response, but I don't think it will have a big impact in terms of performance.

**Comment by ogizanagi** [comment]
For what it is worth: JMSSerializer and FOSRestBundle expose a configuration option to choose if properties containing `null` values should be serialized, and is also part of the serialization context... 
But I agree that the use case is certainly very specific.

**Pull request closed without merging**
