### PR TITLE
Fix wrong denormalization context for related resources

### LINKED ISSUE #303: Denormalization groups do not propagate through relations
Class metadata is loaded using the related resource's own denormalization groups, which is of course wrong (and inconsistent with the [doc]).

For example, if the related resource does not have denormalization groups specified, `SerializerMetadataLoader::loadClassMetadata` returns a `ClassMetadata` with unpopulated `attributesMetadata`.

[doc]: https://github.com/api-platform/doc/blob/4534323849b0dbdca0eea94054c769eb6106bd1b/api-bundle/serialization-groups-and-relations.md

### PR DESCRIPTION
**Pull request by teohhanhui**
Fixes #303

### CODE REVIEW

**Comment by sroze** [comment]
Could you add tests? That way we are sure not to break it again :)

**Comment by teohhanhui** [comment]
Can't say I didn't see that coming! ;)

Will do when I can find the time to...

**Comment by dunglas** [comment]
As it's an annoying issue I think it can be merged without tests (but test are necessary and must be added after).

What do you think?

**Comment by sroze** [comment]
@teohhanhui if you are not available yet to write the test, could you just rebase your branch first?

**Comment by dunglas** [comment]
Thank you @teohhanhui, waiting for the test as well :)

**Pull request merged**
