### PR TITLE
Fix FOSUser integration doc

### PR DESCRIPTION
**Pull request by ogizanagi**
As described in https://github.com/dunglas/DunglasApiBundle/pull/211#discussion_r36580972, the FOSUser integration seems to not be automatic anymore. 

I think it's better as it is, but nothing in the documentation of the bundle refer to the `enable_fos_user` parameter.

### CODE REVIEW

**Comment by theofidry** [comment]
You don't like the idea of having it enabled when the FOSUserBundle is used?

**Comment by ogizanagi** [comment]
Hum, as it acts like a bridge to another third-party bundle, and as we don't have to assume how the bundle is used, I don't think it should be registered automatically.
Of course, it isn't harmful and can be overridden easily by creating another listener with higher priority if needed, but yes, I'm not comfortable with the idea of having it "magically". 
But I guess it's matter of taste than real cons. :smile:

**Comment by dunglas** [comment]
Finally it makes sense because almost all other features are disable by default and an opt in is better in a security pov.

**Comment by sroze** [comment]
I'd love it to be automatically enabled when the FOSUserBundle is enabled. I can't see why it can be a security problem because the user needs to define the resource manually. If the value is `null` (which can be the default value), then we can just check if the bundle is in the installed ones via the `kernel.bundles` parameter.

**Comment by theofidry** [comment]
Aside the security part it's more the fact that you have to enable it that I find annoying. Not that I'm against the principle of enable only what you need, but if you have both bundles enabled, you expect them to work together, not to have to wait to find an issue risen due to find out that you have to manually set this parameter to enable the bridge.

Another choice would be to throw an error if the parameter is not set and the FOSUserBundle used. It would be less user-friendly, but would do the work.

**Comment by sroze** [comment]
Thanks @ogizanagi, the documentation needs to be updated anyway now.

**Pull request merged**
