### PR TITLE
Extract the doc

### PR DESCRIPTION
**Pull request by dunglas**

### CODE REVIEW

**Comment by dupuchba** [comment]
Great, that's a good news :-). By the way, do we keep the actual doc format (e.g markdown) ?

**Comment by dupuchba** [comment]
see => https://github.com/PharkMillups/beautiful-docs

**Comment by soyuka** [comment]
I was thinking of https://github.com/tripit/slate 

There is code for almost every feature, it'd be a nice and detailled way to format docs :).

**Comment by dupuchba** [comment]
@soyuka I have to say, it's quite impressive ! But I feel like it's not well designed for our need.

**Comment by dunglas** [comment]
Here is a demo of the rendered doc: http://api-platform-test.dunglas.com/
I prefer to keep Markdown for now (easier to contribute).

**Comment by dupuchba** [comment]
@dunglas If you are open to my point of view, I think the homepage/landingpage could be better with simpler messages :)

**Comment by dunglas** [comment]
Contributions are welcome! https://github.com/api-platform/website

**Comment by soyuka** [comment]
FIY slate is made using Markdown ([example](https://github.com/tripit/slate/blob/master/source/index.md) => [result](http://tripit.github.io/slate/)).

Nice work @dunglas!

**Comment by dunglas** [comment]
I'm developing an alternative solution named [Calavera](https://github.com/dunglas/calavera). It's a SPA generator using JSON-LD and written in Go and I've used it for new site.

**Comment by dupuchba** [comment]
@dunglas about the home page, I feel like it should be simpler and describe only the value proposition of the api platform : 
- a set of tools to rapidly build high quality standard API in PHP propulse by powerful frameworks

I don't feel like you need to remind people that the web has changed in the 1st page, people who are looking this kind of product already know that :). IMO, you go to deep into details on this 1st page.

Personally on the 1st page I would only talk about the value proposition of API Platform with a big "Getting Started" button.

***

By the way I also go to San Fransisco Live if you want to drink a large american coffee there :-).

**Comment by dunglas** [comment]
@dupuchba thank for your feedback and I'll happily drink large coffees with in SF. I'll wait for other feedback as the first slide already describe the framework and has a big (can be bigger) "Getting started" button.

Maybe that the slide "the web has changed" can be moved at the bottom of the page.

**Pull request merged**
