### PR TITLE
SearchFilter: Allow single/multiple values for any relation

### LINKED ISSUE #365: RFC: SearchFilter - decouple single/multiple values from association cardinality
Given a `Tour` entity with a single-valued (to-one) association named `type` (`TourType`):

Currently we can do:
`/tours?type=/tour_types/1`
but should this be supported as well?
`/tours?type[]=/tour_types/1&type[]=/tour_types/2`

Conversely, given that the `Tour` entity also has a multi-valued (to-many) association named `themes` (`TourTheme`):

Currently we can do:
`/tours?themes[]=/tour_themes/1&themes[]=/tour_themes/2`
but should this be supported as well?
`/tours?themes=/tour_themes/1`

### PR DESCRIPTION
**Pull request by teohhanhui**
... regardless of association cardinality

Fixes #365

### CODE REVIEW

**Comment by dunglas** [comment]
Do you have an idea of why tests fail?

**Comment by teohhanhui** [comment]
There is 1 failing Behat scenario (related to FOSUserBundle) under PHP 7. As for the PHPUnit errors, I have no idea but it was already failing with your previous builds...

**Comment by teohhanhui** [comment]
Should be a Travis-related issue...

**Comment by dunglas** [comment]
Ok LGTM.

**Pull request merged**
