### PR TITLE
Allow getting itemsPerPage from request

### PR DESCRIPTION
**Pull request by amenophis**

### CODE REVIEW

**Comment by dunglas** [comment]
@amenophis first thank for your contribution!

But I don't want to enable this feature by default because:
- it can cause performance issues: if you use a cache proxy such as Varnish, the number of miss will be higher if the number of items by page can be changed server side
- linked to the performance issue, it's a (D)DOS attack vector: increase the number of items by page in a loop and the PHP code will be hit on every requests

Can you add a config flag to enable this feature?
Can you also add some tests (a Behat scenario) and some doc in the readme file?

Thank you.

**Comment by amenophis** [comment]
OK understand, 
i try to use ng-admin, works near well :)

Will try to add all of this now.

**Comment by dunglas** [comment]
Cool. It would be cool if you can share you'r ng-admin config when it works :)

**Comment by amenophis** [comment]
@dunglas It pushed a second commit, can you say me if the apporach is OK for you.
Will try to add scenario to test it after !

**Comment by dunglas** [comment]
Yes, you're on the right direction!

**Comment by amenophis** [comment]
@dunglas OK Nice !
So how can i test different configuration value in behat feature ?

**Comment by dunglas** [comment]
You can create a Kernel able to load different config files depending of the environment and configure different Behat suite loading those different envs.

**Comment by amenophis** [comment]
It can be a bit ugly if we want to test much parameters ...
No ?

**Comment by dunglas** [comment]
Do you know a better way to try different configurations?

**Comment by amenophis** [comment]
Will take a look tonight if i find time :smile:

**Comment by dunglas** [comment]
Cool!

**Comment by amenophis** [comment]
@dunglas Don't found any way to init several kernel ...
Any idea ?

**Comment by dunglas** [comment]
@amenophis can you add some doc. I'll merge the request and add Behat scenarios myself.

**Comment by amenophis** [comment]
ok, will add it tonight

**Comment by amenophis** [comment]
@dunglas Documentation OK. Rebased ans squashed !

**Comment by dunglas** [comment]
Thank you @amenophis

**Pull request merged**
