### PR TITLE
Quality enhancement in ErrorController

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  |no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

cc @meyerbaptiste @ogizanagi

### CODE REVIEW

**Comment by ogizanagi** [comment]
Looks good to me :+1:  
I kept the action signature from the original one, but of course it's useless here.

One thing I suggested in my PR was to eventually move the action into the `HydraController` and also directly use the classic controller notation. Would that make sense ?

**Comment by dunglas** [comment]
Yes it would be more in sync with the spirit of the 1.0 branch.

**Comment by meyerbaptiste** [comment]
:+1:

**Comment by dunglas** [comment]
* Dropped the `ExceptionController`
* Added a new `exceptionAction` to `HydraController`
* Removed the controller as a service

Should be ready to be merged now.

**Comment by ogizanagi** [comment]
:+1:

**Pull request merged**
