### PR TITLE
Rename the ApiPlatform\Builder to ApiPlatform\Core

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Rename the bundle according to [the results of the poll](http://doodle.com/poll/8wz7znhbi2g2kczc).

### CODE REVIEW

**Comment by soyuka** [comment]
Perfect! This should be merge asap :).

**Comment by sroze** [comment]
@soyuka that's actually not used by Symfony, the key is basically the bundle's name which from `ApiPlatformBundle` is `api_platform`. This root key is used only when `append`ing sub configuration trees to an existing one. Anyway, that makes sense. Anyway, I've updated it.

**Comment by sroze** [comment]
AppVeyor is failing for no reasons all the time, so we can skip it, LGTM :+1:

**Comment by soyuka** [comment]
@sroze yeah but it's confusing in the error message:
screenshot from 2016-02-24 12 07 37

Better this way :) thanks!

**Pull request merged**
