### PR TITLE
Added alias for PropertyAccessor

### PR DESCRIPTION
**Pull request by theofidry**
This allows to use our own `PropertyAccessor` more easily.

cc @sroze

### CODE REVIEW

**Comment by dunglas** [comment]
Thank you @theofidry

**Comment by theofidry** [comment]
Is it worth to add a mention in the doc?

**Comment by dunglas** [comment]
IMO this is not necessary. However if you can write a doc on how to improve performance using a custom PropertyAccessor it will be really interesting.

**Comment by theofidry** [comment]
So in a whole chapter dedicated to performance improvements then.

**Comment by dunglas** [comment]
Would be great

**Pull request merged**
