### PR TITLE
Added support for non-hardcoded identifiers (follow up #379)

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #379
| License       | MIT
| Doc PR        | n/a

ping @csarrazi

### CODE REVIEW

**Comment by sroze** [comment]
What about moving the different `if` cases of the `apply` method in different methods? That would definitely improve the readability!

**Comment by dunglas** [comment]
@sroze +1 but in another PR.

**Comment by csarrazi** [comment]
LGTM!

Sorry, I was a bit short on time for that one!

Next step will be to do this on other classes that need this.

**Comment by dunglas** [comment]
And to port it to v2 that now supports composite identifiers.

**Pull request merged**
