### PR TITLE
Support for Hydra's PartialCollectionView

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #353
| License       | MIT
| Doc PR        | n/a

@lanthaler If you have some time, can you take a look at the generated output to see if it's valid according to the new spec?

There are 2 points where I'm not sure of the conformance:

* When filters are applied, the `totalItems` field is removed because it would slow down the API to make another SQL `COUNT()` query to get the number of element of the without filters applied
* I'm not sure if what I've done is correct when filters are applied to paged collections.

Thanks in advance.

### CODE REVIEW

**Comment by teohhanhui** [comment]
I can see still a lot of discussion going on about this in the mailing list. Is it stable enough for us to implement?

**Comment by dunglas** [comment]
`PartialCollectionView` has been added to the online spec: http://www.hydra-cg.com/spec/latest/core/#h-collections so I think it's ok to change that now.

For filters, nothing seems to be ready yet so it's better to wait.

**Comment by leesiongchan** [comment]
> When filters are applied, the totalItems field is removed because it would slow down the API to make another SQL COUNT() query to get the number of element of the without filters applied

@dunglas I think totalItems should corresponding to the current result but not the result without filters applied.

**Comment by teohhanhui** [comment]
`hydra:totalItems` is described as such in the spec:

> The total number of items referenced by a collection.

And if we look at http://www.hydra-cg.com/spec/latest/core/#collections it specifically uses "results of a search query" as an example. This strongly suggests that the collection is the filtered collection.

**Pull request merged**
