### PR TITLE
Added use case with JMSSerializer

### PR DESCRIPTION
**Pull request by theofidry**
Follow up of #229.

### CODE REVIEW

**Comment by ogizanagi** [comment]
:+1:

**Comment by ogizanagi** [comment]
I think a little note about checking the previous usages of the JMS Serializer implies correctly referencing to it using `@jms_serializer` / `$container->get('jms_serializer')` and not just `serializer`.

**Comment by sroze** [comment]
I think that the best way of tackling this problem is to solve it, instead of listing it as a known one. What I suggest is to allow to configure the name of the serializer used via the configuration of the bundle, which can also be guessed and that will allow us to potentially create a JMS serializer bridge.

**Comment by theofidry** [comment]
So we can put this as a temporary measure and add a ticket for a JMS Serializer bridge?

**Comment by dunglas** [comment]
IMO the doc is enough. It's a JMS SerializerBundle bug (it's not a good practice to replace a default Symfony service by another one not implementing the same interface).
And the JMS Serializer bridge will make the maintenance more complex (several type of metadata, of groups...) for no concrete gain.

**Comment by ogizanagi** [comment]
We can keep mentioning the JMS issue in the doc while automatically disabling the `enable_short_alias` parameter when the JMS Serializer is installed. But this echoes the previous debate about automatically enable / doing things about third party bundles (https://github.com/dunglas/DunglasApiBundle/pull/216#issuecomment-129042274).

**Pull request merged**
