### PR TITLE
Fix tests for #369

### PR DESCRIPTION
**Pull request by teohhanhui**

### CODE REVIEW

**Comment by dunglas** [comment]
Which branch are you targeting? Master?

**Comment by teohhanhui** [comment]
This is the correct branch, for #369

**Comment by teohhanhui** [comment]
Or would you like me to open another PR to replace #369?

**Comment by dunglas** [comment]
Ok. Can you fix CS as well?

**Comment by dunglas** [comment]
Nevermind, StyleCI is wrong.

**Comment by dunglas** [comment]
But it should be `@var ResourceInterface` and not `Resource`

**Comment by teohhanhui** [comment]
styleci

**Comment by dunglas** [comment]
Thanks @teohhanhui

**Pull request merged**
