### PR TITLE
Fix documentations links on performances

### PR DESCRIPTION
**Pull request by soyuka**

### CODE REVIEW

**Comment by theofidry** [comment]
Can you also fix the link in the table of content please?

**Comment by soyuka** [comment]
Missed that thanks.

**Comment by dunglas** [comment]
Why adding a final `s`? Symfony doesn't: http://symfony.com/doc/current/book/performance.html
Django use `performance` too: https://docs.djangoproject.com/en/1.8/topics/performance/

**Comment by theofidry** [comment]
If we keep without the final `s` then there is just the broken link to resolve in the chapters Security and Angular Integration.

**Comment by soyuka** [comment]
@theofidry indeed, I choose to add an "s" instead of removing it in Security and Angular. I think that usually we speak about "performances" in general but if you want I can change this to "performance" everywhere. Let me know.

**Comment by theofidry** [comment]
Well it was more logical to me with the `s` so I didn't give much though on this but as @dunglas pointed out, it seems more correct to talk about `Performance` rather than `Performances`.

**Comment by dunglas** [comment]
I think (but not sure about it that we usually use "performances" in french but "performance" in english). Maybe @sroze has an opinion about that as he is now a senior english speaker.

**Comment by soyuka** [comment]
I made a new PR just choose which one you prefer and close the other one ;).

@dunglas I think you're right, we speak about "performance" for a general case. The plural would be used to discuss a pianist's "performances" on different occasions for example.

**Comment by soyuka** [comment]
Closing as #239 has been merged.

**Pull request closed without merging**
