### PR TITLE
Use the built-in Symfony DateTimeNormalizer

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by sroze** [comment]
Is the Symfony serializer using the ATOM format by default?

**Comment by dunglas** [comment]
@sroze Yes (it's basically the DateTimeNormalizer of API Platform moved to the Symfony Serializer https://github.com/symfony/symfony/pull/17411). It's why tests pass.

**Comment by sroze** [comment]
Nice! :+1:

**Comment by teohhanhui** [comment]
So how do we specify a custom format for a property (other than resorting to custom normalizers)?

**Pull request merged**
